# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SARFloodATDialog
                                 A QGIS plugin
 SAR Flood Mapping
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-02
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Lei Wang
        email                : leiwang@lsu.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
GEEData_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'geeDataDialog.ui'))
     
class geeDataDialog(QtWidgets.QDialog, GEEData_FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(geeDataDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        
PREDATA_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'prepare_image.ui'))
     
class PrepareImageDialog(QtWidgets.QDialog, PREDATA_FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PrepareImageDialog, self).__init__(parent)
        self.setupUi(self)
        
        
RGROW_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'rgrow_dialog.ui'))
     
class RegionGrowDialog(QtWidgets.QDialog, RGROW_FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(RegionGrowDialog, self).__init__(parent)
        self.setupUi(self)
        
        
RSPIT_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'rsplit_dialog.ui'))
     
class RegionSplitDialog(QtWidgets.QDialog, RSPIT_FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(RegionSplitDialog, self).__init__(parent)
        self.setupUi(self)        
        
        
BMODAL_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'bimodal_dialog.ui'))
     
class BimodalDialog(QtWidgets.QDialog, BMODAL_FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(BimodalDialog, self).__init__(parent)
        self.setupUi(self)    
        
        
FILTER_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'filter_dialog.ui'))
     
class FilterDialog(QtWidgets.QDialog, FILTER_FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(FilterDialog, self).__init__(parent)
        self.setupUi(self)
        
INTERP_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'interp_dialog.ui'))
     
class InterpDialog(QtWidgets.QDialog, INTERP_FORM_CLASS):
    """Interpolate threshold and compare it the the SAR image
    """
    def __init__(self, parent=None):
        """Constructor."""
        super(InterpDialog, self).__init__(parent)
        self.setupUi(self)
        
ALL_FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'allSteps.ui'))
     
class AllStepsDialog(QtWidgets.QDialog, ALL_FORM_CLASS):
    """Interpolate threshold and compare it the the SAR image
    """
    def __init__(self, parent=None):
        """Constructor."""
        super(AllStepsDialog, self).__init__(parent)
        self.setupUi(self)